### ISSUE TITLE
RangeError (index): Invalid value: Valid value range is empty: 0

### ISSUE THREAD

**Issue by jalvespinto** [rickypid/flutter_expandable_table#11]
For the tablebody I keep getting this error in the `_buildBodyColumns` method because the `visibleColumn` is empty at first.
```
for (Widget cell in cells) {
        cellsRow.add(ExpandableTableCell(
          child: cell,
          height: row.height,
          width: ExpandableTableData.of(context).cellWidth,
          horizontalExpanded:
              ExpandableTableData.of(context).visibleColumn[x] == true,
          verticalExpanded: rowParent != null ? rowParent.isExpanded : true,
        ));
        x++;
      }
```
If I hot reload the emulator after going to the page it works.

**Comment by sithu-aung** [comment]
I am facing the same error too. Haven't any idea to solve this ?

**Comment by nachiketghelani54** [comment]
Hello there,
I have data and its contains subdata when i Expanded Data then subdata Range is Empty, But SubData is not Empty.

If anyone has solution please inform.

thank you all in advance.

**Comment by madebyframe** [comment]
> For the tablebody I keep getting this error in the `_buildBodyColumns` method because the `visibleColumn` is empty at first.
> 
> ```
> for (Widget cell in cells) {
>         cellsRow.add(ExpandableTableCell(
>           child: cell,
>           height: row.height,
>           width: ExpandableTableData.of(context).cellWidth,
>           horizontalExpanded:
>               ExpandableTableData.of(context).visibleColumn[x] == true,
>           verticalExpanded: rowParent != null ? rowParent.isExpanded : true,
>         ));
>         x++;
>       }
> ```
> 

I noticed that this work-around seems to work by adding a sanity check on the offending index value:
  ```
 for (Widget cell in cells) {
        cellsRow.add(ExpandableTableCell(
          child: cell,
          height: row.height,
          width: ExpandableTableData.of(context).cellWidth,
          horizontalExpanded:
              **ExpandableTableData.of(context).visibleColumn.asMap().containsKey(x) &&**
              ExpandableTableData.of(context).visibleColumn[x] == true,
          verticalExpanded: rowParent != null ? rowParent.isExpanded : true,
        ));
```

**Comment by nachiketghelani54** [comment]
@madebyframe  

we created header data list statically based on data. we can add data to header data dynamically but we can not able to add header children dynamically and thats why range error is generating.

**Comment by lottoforecaster** [comment]
> I am facing the same error too. Haven't any idea to solve this ?

+1

**Comment by rickypid** [comment]
Hi everyone,

I'm sorry for the problem encountered but I didn't have time to dedicate to this project, finally in a few weeks I will release a new 2.0 version which will contain some requests that have been made to me, also this one https://github.com/rickypid/flutter_expandable_table/ issues/9, both for row height and column width.

I will notify you as soon as it is published and ask for some feedback.

Thank you.

**Comment by rickypid** [comment]
Hi everyone,
[here](https://pub.dev/packages/flutter_expandable_table/versions/2.0.0-beta.1) you can find the new release `v2.0.0-beta.1` (in beta) with some improvements and improved/added features.

It requires some adaptation from the previous 1.x version, but it was necessary to improve the code base.

Thank you for waiting, I hope you will give me some feedback. 😄

**Comment by Somtobro** [comment]
Not to sound ungrateful but come on..don't make a package is it isn't working
Was pulling my hair out All day Wondering why this isn't working then I finally came here
