### ISSUE TITLE
Example Code Android Emulator Pixel XML API 33 Overflow Errors

### ISSUE THREAD

**Issue by DktPhl2019** [rickypid/flutter_expandable_table#18]
Hello

Running example code on Android Emulator Pixel XML API 33 shows Overflow error by 34 pixels for simple table and 84 pixels for expandable table.

Please fix.

Thank You

**Comment by rickypid** [comment]
Hi @DktPhl2019,

Thanks for reporting but the example is simply for demonstration purposes and is not designed to be responsive. I believe that for demonstration purposes it is not a problem if it does not adapt to every type of device.
