### ISSUE TITLE
select a row 

### ISSUE THREAD

**Issue by Ouya-Hamou** [rickypid/flutter_expandable_table#2]
Hi !!
I want to select a row and make some editing on it, is there a way to do it?

**Comment by rickypid** [comment]
Hi @Ouya-Hamou ,

This project was initially born to display a reduced content of information, so it was conceived simply as an animated grid. at the moment I don't have much time to devote to this implementation although I think it's a great feature to implement.

If you want you can contribute to the project with a PR to implement this feature, I will follow you and help you in this.

**Comment by rickypid** [comment]
Hi, to achieve this you can simply change the background of your row and change the wedges inside your row making it editable when clicked. This library was only meant as a scaffolding for your wedgets.
