### ISSUE TITLE
UI Overflow

### ISSUE THREAD

**Issue by mabrar312** [rickypid/flutter_expandable_table#20]
If there are children in a row, and there are no rows to the parent row UI of the row's first cell that has children is getting overflow
![image](https://github.com/rickypid/flutter_expandable_table/assets/138851831/b2749b7f-9b70-494e-abfe-ea9362bec8de)

**Comment by RichiB20** [comment]
Hi @mabrar312, it seems we don't see this problem, could you please provide us the code you used for creating the table to verify this?

**Comment by irshad-hz** [comment]
is there any way to remove the lines inbetween each cells, even after giving margin as zero it is still visible.

**Comment by RichiB20** [comment]
Hi @irshad-hz, we noticed this problem and we're investigating why this happens, we think that is something related to Flutter beacuse we don't insert any margin or padding in the package. 
If you have all the cells of the same color there is a simple workaround: wrap your table with a Stack and insert a Container with the color of your cells before the table, in this way the background of the table will have the same color of the cells.
Example:
```
Stack(
  children: [
    Container(color: primaryColor,),
    _buildSimpleTable(),
  ],
)
```
