### ISSUE TITLE
Reorder rows

### ISSUE THREAD

**Issue by PhilipNell-258** [rickypid/flutter_expandable_table#23]
Hello there.

I really enjoy your take on the expandable data grid. Will it be possible to add a feature to drag and drop rows within the table to a new location?

Similar to this:
https://raw.githubusercontent.com/welchi/nested_reorderable_list/main/example/gifs/nested_reorderable_list_demo.gif

**Comment by rickypid** [comment]
Hi @ddkwork,

As I have indicated in other issues, the library was not created to implement data processing internally but only deals with managing the layout.
