### ISSUE TITLE
more feature like

### ISSUE THREAD

**Issue by ddkwork** [rickypid/flutter_expandable_table#24]
https://primevue.org/treetable

**Comment by motorahul** [comment]
<img width="741" alt="image" src="https://github.com/rickypid/flutter_expandable_table/assets/43537334/39f0fe10-d592-4651-9c15-f76896b0b737">
can you please guide me here how to make dynamic table  from rest apis here and want perform some action on each row 
thanks

**Comment by rickypid** [comment]
Hi @motorahul,

Sorry for the late response, do you still need support?

**Comment by rickypid** [comment]
> https://primevue.org/treetable

Hi @ddkwork,

As I have indicated in other issues, the library was not created to implement data processing internally but only deals with managing the layout.
