### ISSUE TITLE
Request to add horizontal scroll bar functionality

### ISSUE THREAD

**Issue by windinternet** [rickypid/flutter_expandable_table#27]
I am attempting to display my data on PC devices (Windows, Mac OS) using this library, and it's working very well! I must say this is a praiseworthy library, but I encountered an issue. Most PC devices do not have touch screens or touchpads, and by default, there is no explicit horizontal scrollbar, causing these users to be unable to view all the data. Therefore, I request the addition of an explicit horizontal scrollbar to accommodate more PC devices, thank you!

**Comment by rickypid** [comment]
@windinternet Thanks for the tip.

**Comment by rickypid** [comment]
@RichiB20 can you see about putting it on the roadmap? I think it's a quick thing.

**Comment by RichiB20** [comment]
Hi @windinternet, the horizontal scroll bar has been implemented in the new 2.1.0 version. You can manage the visibility of the scrollabars with the `visibleScrollbar` parameter, you can also manage the visibility of thumb and track of scrollabars with `thumbVisibilityScrollbar` and `trackVisibilityScrollbar` parameters.
