### ISSUE TITLE
Elements Don't Hide: Flutter Form Builder 2

### ISSUE THREAD

**Issue by phillipshaong** [rickypid/flutter_expandable_table#28]
I am using elements from `flutter_form_builder`(9.1.1), and want to use form builder elements within the expanded table. 

For typical Flutter elements like `Text` or `ElevatedButton`, they are hidden once the row collapses. 

However, for `flutter_form_builder` elements, they don't hide very well. 

<img width="653" alt="image" src="https://github.com/rickypid/flutter_expandable_table/assets/64993172/c48a74db-cb03-4ef6-b7c0-2180ce624445">

<img width="656" alt="image" src="https://github.com/rickypid/flutter_expandable_table/assets/64993172/b70ca7c3-7ab6-4688-831e-2d09367f8a57">

As you can see, the checkbox from `FormBuilderCheckbox` still shows, and the boarders and text from the `FormBuilderDateTimePicker` show as well. The same behavior occurs with other elements in the library.

**Comment by rickypid** [comment]
@phillipshaong can you give me an example?

**Comment by NJashwanth** [comment]
@phillipshaong   I was also dealing with a similar issue. I was able to resolve the issue by using the builder parameter and hiding the widget.
