### ISSUE TITLE
Filter data

### ISSUE THREAD

**Issue by Ouya-Hamou** [rickypid/flutter_expandable_table#3]
Hi!!
I want to add some Filtering to my table. is that possible? and how?

**Comment by rickypid** [comment]
Hi @Ouya-Hamou ,

This project was initially born to display a reduced content of information, so it was conceived simply as an animated grid. at the moment I don't have much time to devote to this implementation although I think it's a great feature to implement.

If you want you can contribute to the project with a PR to implement this feature, I will follow you and help you in this.
