### ISSUE TITLE
Does the flutter_expandable_table package support pagination of items?

### ISSUE THREAD

**Issue by NJashwanth** [rickypid/flutter_expandable_table#32]
Hi,  I'm currently exploring the flutter_expandable_table package for displaying tabular data in my Flutter application. One feature I'm particularly interested in is pagination, which allows for efficient navigation through large datasets by displaying a subset of items per page.

Could you please confirm whether the flutter_expandable_table package includes built-in support for pagination of items? If so, I'd appreciate any guidance on how to implement and configure this feature within the package.

Thank you in advance for your assistance!

**Comment by rickypid** [comment]
Hi @NJashwanth ,

Unfortunately at the moment the package does not support pagination functionality, I am considering implementation in a possible 3.0 refactoring. We will see in the coming weeks if I have the time to devote to this activity.

I'll close for now and put it back in #26
