### ISSUE TITLE
Expandable row inside Expnadable Row

### ISSUE THREAD

**Issue by nikhil-viewzen** [rickypid/flutter_expandable_table#35]
Is it possible to create a row inside another row Similar to this screenshot.Because in the examples that row is replaced with legend
![image](https://github.com/user-attachments/assets/51f9a1d0-9f15-4592-b297-0617f2ad7730)

**Comment by rickypid** [comment]
Hello @nikhil-viewzen , absolutely yes, just do not populate the legend parameter and the row will behave like a normal row.
