### ISSUE TITLE
RangeError (index): Index out of range: no indices are valid: 0

### ISSUE THREAD

**Issue by nikhil-viewzen** [rickypid/flutter_expandable_table#36]
I am using version 1.1.1 and I am getting RangeError (index): Index out of range: no indices are valid: 0 error
![image](https://github.com/user-attachments/assets/8a9e1df2-5aae-4633-a729-bcc57d06b611)

**Comment by rickypid** [comment]
Hi @nikhil-viewzen, I would recommend using the latest version v2.1.0.

**Comment by nikhil-viewzen** [comment]
I am using flutter 3.7.3 and 2.1.0 is not supported in this version
![image](https://github.com/user-attachments/assets/9218ec1e-8b27-4901-b130-5d53708099d5)

**Comment by rickypid** [comment]
you should provide me with a more detailed error stack. The v3.7.3 is a very old version ([3.7.3](https://github.com/flutter/flutter/releases/tag/3.7.3) (Feb 9, 2023)) I don't think I will be able to test it quickly on my PC.

**Comment by nikhil-viewzen** [comment]
![image](https://github.com/user-attachments/assets/7abfb5a9-e619-4aa6-bf1f-5c527a5b2e84)

<details><summary>Stack</summary>

The following IndexError was thrown building ExpandableTableBody(dirty, dependencies: [_ExpandableTableDataInherited], state: _ExpandableTableBodyState#684df):
RangeError (index): Index out of range: no indices are valid: 0

The relevant error-causing widget was: 
  ExpandableTable ExpandableTable:file:///home/administrator/development/appverse-web-forms/lib/routes/formview/form_view_page.dart:756:49
When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/js_array.dart 581:7                 _get]
packages/flutter_expandable_table/src/body.dart 102:45                            [_buildBodyColumns]
packages/flutter_expandable_table/src/body.dart 142:41                            <fn>
packages/flutter_expandable_table/src/body.dart 142:71                            build
packages/flutter/src/widgets/framework.dart 5080:27                               build
packages/flutter/src/widgets/framework.dart 4968:15                               performRebuild
packages/flutter/src/widgets/framework.dart 5133:11                               performRebuild
packages/flutter/src/widgets/framework.dart 4690:5                                rebuild
packages/flutter/src/widgets/framework.dart 4950:5                                [_firstBuild]
packages/flutter/src/widgets/framework.dart 5124:11                               [_firstBuild]
packages/flutter/src/widgets/framework.dart 4944:5                                mount
packages/flutter/src/widgets/framework.dart 3953:15                               inflateWidget
packages/flutter/src/widgets/framework.dart 3682:18                               updateChild
packages/flutter/src/widgets/framework.dart 4993:16                               performRebuild
packages/flutter/src/widgets/framework.dart 4690:5                                rebuild
packages/flutter/src/widgets/framework.dart 4950:5                                [_firstBuild]
packages/flutter/src/widgets/framework.dart 4944:5                                mount
packages/flutter/src/widgets/framework.dart 3953:15                               inflateWidget
packages/flutter/src/widgets/framework.dart 6512:36                               inflateWidget
packages/flutter/src/widgets/framework.dart 6524:32                               mount
packages/flutter/src/widgets/framework.dart 3953:15                               inflateWidget
packages/flutter/src/widgets/framework.dart 3682:18                               updateChild
packages/flutter/src/widgets/framework.dart 4993:16                               performRebuild
packages/flutter/src/widgets/framework.dart 4690:5                                rebuild
packages/flutter/src/widgets/framework.dart 4950:5                                [_firstBuild]
packages/flutter/src/widgets/framework.dart 4944:5                                mount
packages/flutter/src/widgets/framework.dart 3953:15                               inflateWidget
packages/flutter/src/widgets/framework.dart 3682:18                               updateChild
packages/flutter/src/widgets/framework.dart 4993:16                               performRebuild
packages/flutter/src/widgets/framework.dart 5133:11                               performRebuild
packages/flutter/src/widgets/framework.dart 4690:5                                rebuild
packages/flutter/src/widgets/framework.dart 4950:5                                [_firstBuild]
packages/flutter/src/widgets/framework.dart 5124:11                               [_firstBuild]
packages/flutter/src/widgets/framework.dart 4944:5                                mount
packages/flutter/src/widgets/framework.dart 3953:15                               inflateWidget
packages/flutter/src/widgets/framework.dart 3682:18                               updateChild
packages/flutter/src/widgets/framework.dart 4993:16                               performRebuild
packages/flutter/src/widgets/framework.dart 4690:5                                rebuild
packages/flutter/src/widgets/framework.dart 4950:5                                [_firstBuild]
packages/flutter/src/widgets/framework.dart 4944:5                                mount
packages/flutter/src/widgets/framework.dart 3953:15                               inflateWidget
packages/flutter/src/widgets/framework.dart 3682:18                               updateChild
packages/flutter/src/widgets/framework.dart 4993:16                               performRebuild
packages/flutter/src/widgets/framework.dart 5133:11                               performRebuild
packages/flutter/src/widgets/framework.dart 4690:5                                rebuild
packages/flutter/src/widgets/framework.dart 4950:5                                [_firstBuild]
packages/flutter/src/widgets/framework.dart 5124:11                               [_firstBuild]
packages/flutter/src/widgets/framework.dart 4944:5                                mount
packages/flutter/src/widgets/framework.dart 3953:15                               inflateWidget
packages/flutter/src/widgets/framework.dart 3682:18                               updateChild
packages/flutter/src/widgets/framework.dart 4993:16                               performRebuild
packages/flutter/src/widgets/framework.dart 5133:11                               performRebuild
packages/flutter/src/widgets/framework.dart 4690:5                                rebuild
packages/flutter/src/widgets/framework.dart 4950:5                                [_firstBuild]
packages/flutter/src/widgets/framework.dart 5124:11                               [_firstBuild]
packages/flutter/src/widgets/framework.dart 4944:5                                mount
packages/flutter/src/widgets/framework.dart 3953:15                               inflateWidget
packages/flutter/src/widgets/framework.dart 3682:18                               updateChild
packages/flutter/src/widgets/framework.dart 6377:14                               mount
packages/flutter/src/widgets/framework.dart 3953:15                               inflateWidget
packages/flutter/src/widgets/framework.dart 3682:18                               updateChild
packages/flutter/src/widgets/framework.dart 6377:14                               mount
packages/flutter/src/widgets/framework.dart 3953:15                               inflateWidget
packages/flutter/src/widgets/framework.dart 3682:18                               updateChild
packages/flutter/src/widgets/framework.dart 4993:16                               performRebuild
packages/flutter/src/widgets/framework.dart 4690:5                                rebuild
packages/flutter/src/widgets/framework.dart 4950:5                                [_firstBuild]
packages/flutter/src/widgets/framework.dart 4944:5                                mount
packages/flutter/src/widgets/framework.dart 3953:15                               inflateWidget
packages/flutter/src/widgets/framework.dart 3682:18                               updateChild
packages/flutter/src/widgets/framework.dart 6377:14                               mount
packages/flutter/src/widgets/framework.dart 3953:15                               inflateWidget
packages/flutter/src/widgets/framework.dart 3682:18                               updateChild
packages/flutter/src/widgets/framework.dart 6377:14                               mount
packages/flutter/src/widgets/framework.dart 3953:15                               inflateWidget
packages/flutter/src/widgets/framework.dart 6512:36                               inflateWidget
packages/flutter/src/widgets/framework.dart 3682:18                               updateChild
packages/flutter/src/widgets/framework.dart 6041:32                               updateChildren
packages/flutter/src/widgets/framework.dart 6537:17                               update
packages/flutter/src/widgets/framework.dart 3660:14                               updateChild
packages/flutter/src/widgets/framework.dart 6384:14                               update
packages/flutter/src/widgets/framework.dart 3660:14                               updateChild
packages/flutter/src/widgets/framework.dart 4993:16                               performRebuild
packages/flutter/src/widgets/framework.dart 5133:11                               performRebuild
packages/flutter/src/widgets/framework.dart 4690:5                                rebuild
packages/flutter/src/widgets/framework.dart 5156:5                                update
packages/flutter/src/widgets/framework.dart 3660:14                               updateChild
packages/flutter/src/widgets/framework.dart 4993:16                               performRebuild
packages/flutter/src/widgets/framework.dart 5133:11                               performRebuild
packages/flutter/src/widgets/framework.dart 4690:5                                rebuild
packages/flutter/src/widgets/framework.dart 5156:5                                update
packages/flutter/src/widgets/framework.dart 3660:14                               updateChild
packages/flutter/src/widgets/framework.dart 6384:14                               update
packages/flutter/src/widgets/framework.dart 3660:14                               updateChild
packages/flutter/src/widgets/framework.dart 6384:14                               update
packages/flutter/src/widgets/framework.dart 3660:14                               updateChild
packages/flutter/src/widgets/framework.dart 4993:16                               performRebuild
packages/flutter/src/widgets/framework.dart 5133:11                               performRebuild
packages/flutter/src/widgets/framework.dart 4690:5                                rebuild
packages/flutter/src/widgets/framework.dart 5156:5                                update
packages/flutter/src/widgets/framework.dart 3660:14                               updateChild
packages/flutter/src/widgets/framework.dart 4993:16                               performRebuild
packages/flutter/src/widgets/framework.dart 4690:5                                rebuild
packages/flutter/src/widgets/framework.dart 5301:5                                update
packages/flutter/src/widgets/framework.dart 3660:14                               updateChild
packages/flutter/src/widgets/framework.dart 4993:16                               performRebuild
packages/flutter/src/widgets/framework.dart 4690:5                                rebuild
packages/flutter/src/widgets/framework.dart 5301:5                                update
packages/flutter/src/widgets/framework.dart 3660:14                               updateChild
packages/flutter/src/widgets/framework.dart 4993:16                               performRebuild
packages/flutter/src/widgets/framework.dart 5133:11                               performRebuild
packages/flutter/src/widgets/framework.dart 4690:5                                rebuild
packages/flutter/src/widgets/framework.dart 5156:5                                update
packages/flutter/src/widgets/framework.dart 3660:14                               updateChild
packages/flutter/src/widgets/framework.dart 4993:16                               performRebuild
packages/flutter/src/widgets/framework.dart 4690:5                                rebuild
packages/flutter/src/widgets/framework.dart 5044:5                                update
packages/flutter/src/widgets/framework.dart 3660:14                               updateChild
packages/flutter/src/widgets/sliver.dart 1451:37                                  updateChild
packages/flutter/src/widgets/sliver.dart 1352:35                                  processElement
dart-sdk/lib/core/iterable.dart 325:35                                            forEach
packages/flutter/src/widgets/sliver.dart 1399:18                                  performRebuild
packages/flutter/src/widgets/sliver.dart 1328:7                                   update
packages/flutter/src/widgets/framework.dart 3660:14                               updateChild
packages/flutter/src/widgets/framework.dart 4993:16                               performRebuild
packages/flutter/src/widgets/framework.dart 4690:5                                rebuild
packages/flutter/src/widgets/framework.dart 5301:5                                update
packages/flutter/src/widgets/framework.dart 3660:14                               updateChild
packages/flutter/src/widgets/framework.dart 6384:14                               update
packages/flutter/src/widgets/framework.dart 3660:14                               updateChild
packages/flutter/src/widgets/framework.dart 5981:32                               updateChildren
packages/flutter/src/widgets/framework.dart 6537:17                               update
packages/flutter/src/widgets/viewport.dart 237:11                                 update
packages/flutter/src/widgets/framework.dart 3660:14                               updateChild
packages/flutter/src/widgets/framework.dart 6384:14                               update


</details>

**Comment by rickypid** [comment]
@nikhil-viewzen I think the problem is related to your code, I think you are not passing the column arrays in each row correctly, as I told you I find it complicated to test such an old version now, unfortunately I don't have much time to do this test.
