### ISSUE TITLE
Dynamic cell width

### ISSUE THREAD

**Issue by patrikbadanjak** [rickypid/flutter_expandable_table#9]
Would it be possible to make a column as wide as it's widest cell? Or be the width of a header cell in case it's the widest.

**Comment by rickypid** [comment]
Hi @patrikbadanjak ,

At the moment this functionality has not yet been implemented.

If you want you can contribute to the project with a PR to implement this feature, I will follow you and help you in this.

**Comment by rickypid** [comment]
hi @patrikbadanjak,

[here](https://pub.dev/packages/flutter_expandable_table/versions/2.0.0-beta.1) you can find the new release `v2.0.0-beta.1` (in beta), this release contains the functionality you requested in this issue.

Thank you for waiting, I hope you will give me some feedback. 😄

**Comment by patrikbadanjak** [comment]
We've dropped the feature that used the table, but I will be sure to provide feedback once we get back to working on it. Thank you for the update!
